import {metaKeyName, shortMetaKeyName} from "src/utils/meta-key-name";

export const keyboardKeyMapping: { [key: string]: string | undefined } = {
    "Ctrl": "Ctrl",
    "ControlLeft": "Л. Ctrl",
    "ControlRight": "П. Ctrl",
    "Shift": "Shift",
    "ShiftLeft": "Л. Shift",
    "ShiftRight": "П. Shift",
    "Alt": "Alt",
    "AltLeft": "Л. Alt",
    "AltRight": "П. Alt",
    "Meta": metaKeyName,
    "MetaLeft": "Л. " + metaKeyName,
    "MetaRight": "П. " + metaKeyName,
    "Escape": "Esc",
    "Equal": "=",
    "Minus": "-",
    "BracketLeft": "[",
    "BracketRight": "]",
    "Backslash": "\\",
    "Semicolon": ";",
    "Quote": "'",
    "Comma": ",",
    "Period": ".",
    "Slash": "/",
    "Space": "Пробел",
    "ArrowLeft": "←",
    "ArrowUp": "↑",
    "ArrowRight": "→",
    "ArrowDown": "↓"
}

export const shortKeyboardKeyMapping: { [key: string]: string | undefined } = {
    "Ctrl": "^",
    "ControlLeft": "^",
    "ControlRight": "^",
    "Meta": shortMetaKeyName,
    "MetaLeft": shortMetaKeyName,
    "MetaRight": shortMetaKeyName,
    "Shift": "⇧",
    "ShiftRight": "⇧",
    "ShiftLeft": "⇧",
    "Alt": "⎇",
    "AltLeft": "⎇",
    "AltRight": "⎇",
    "Escape": "Esc",
    "Equal": "=",
    "Minus": "-",
    "BracketLeft": "[",
    "BracketRight": "]",
    "Backslash": "\\",
    "Semicolon": ";",
    "Quote": "'",
    "Comma": ",",
    "Period": ".",
    "Slash": "/",
    "Space": "␣",
    "ArrowLeft": "←",
    "ArrowUp": "↑",
    "ArrowRight": "→",
    "ArrowDown": "↓"
}