import 'src/entity/types/bullet-16mm/client-prefab'
import 'src/entity/types/bullet-42mm/client-prefab'
import 'src/entity/types/bullet-bomb/client-prefab'
import 'src/entity/types/bullet-cannonball/client-prefab'
import 'src/entity/types/bullet-mine/client-prefab'
import 'src/entity/types/bullet-mortar-ball/client-prefab'

import 'src/entity/types/timer/client-prefab'
import 'src/entity/types/flag/client-prefab'
import 'src/entity/types/chat/client-prefab'

import 'src/entity/types/controller-ctf/client-prefab'
import 'src/entity/types/controller-dm/client-prefab'
import 'src/entity/types/controller-tdm/client-prefab'
import 'src/entity/types/controller-freeroam/client-prefab'

import 'src/entity/types/tank-bigboi/client-prefab'
import 'src/entity/types/tank-tesla/client-prefab'
import 'src/entity/types/tank-bomber/client-prefab'
import 'src/entity/types/tank-nasty/client-prefab'
import 'src/entity/types/tank-mortar/client-prefab'
import 'src/entity/types/tank-sniper/client-prefab'
import 'src/entity/types/tank-shotgun/client-prefab'
import 'src/entity/types/tank-monster/client-prefab'
import 'src/entity/types/tank-tiny/client-prefab'

import 'src/entity/types/weapon-single-barrelled/client-prefab'
import 'src/entity/types/weapon-double-barreled/client-prefab'
import 'src/entity/types/weapon-stungun/client-prefab'
import 'src/entity/types/weapon-shotgun/client-prefab'
import 'src/entity/types/weapon-flamethrower/client-prefab'

import 'src/entity/types/effect-flame/client-prefab'
import 'src/entity/types/effect-pellets/client-prefab'
import 'src/entity/types/effect-world-explosion/client-prefab'
import 'src/entity/types/effect-sound/client-prefab'

import 'src/entity/types/group/client-prefab'
import 'src/entity/types/tilemap/client-prefab'
import 'src/entity/types/spawn-zone/client-prefab'