import 'src/entity/types/bullet-16mm/client-side/client-prefab'
import 'src/entity/types/bullet-42mm/client-side/client-prefab'
import 'src/entity/types/bullet-bomb/client-side/client-prefab'
import 'src/entity/types/bullet-cannonball/client-side/client-prefab'
import 'src/entity/types/bullet-mine/client-side/client-prefab'
import 'src/entity/types/bullet-mortar-ball/client-side/client-prefab'

import 'src/entity/types/timer/client-side/client-prefab'
import 'src/entity/types/flag/client-side/client-prefab'

import 'src/entity/types/controller-ctf/client-side/client-prefab'
import 'src/entity/types/controller-dm/client-side/client-prefab'
import 'src/entity/types/controller-tdm/client-side/client-prefab'

import 'src/entity/types/tank-bigboi/client-side/client-prefab'
import 'src/entity/types/tank-tesla/client-side/client-prefab'
import 'src/entity/types/tank-bomber/client-side/client-prefab'
import 'src/entity/types/tank-nasty/client-side/client-prefab'
import 'src/entity/types/tank-mortar/client-side/client-prefab'
import 'src/entity/types/tank-sniper/client-side/client-prefab'
import 'src/entity/types/tank-shotgun/client-side/client-prefab'
import 'src/entity/types/tank-monster/client-side/client-prefab'
import 'src/entity/types/tank-tiny/client-side/client-prefab'

import 'src/entity/types/weapon-single-barrelled/client-prefab'
import 'src/entity/types/weapon-double-barreled/client-prefab'
import 'src/entity/types/weapon-stungun/client-prefab'
import 'src/entity/types/weapon-shotgun/client-prefab'
import 'src/entity/types/weapon-flamethrower/client-prefab'

import 'src/entity/types/effect-flame/client-side/client-prefab'
import 'src/entity/types/effect-pellets/client-side/client-prefab'
import 'src/entity/types/effect-world-explosion/client-side/client-prefab'
import 'src/entity/types/effect-sound/client-side/client-prefab'

import 'src/entity/types/tilemap/client-side/client-prefab'