
import 'src/entity/types/bullet-16mm/prefab'
import 'src/entity/types/bullet-42mm/prefab'
import 'src/entity/types/bullet-bomb/prefab'
import 'src/entity/types/bullet-cannonball/prefab'
import 'src/entity/types/bullet-mine/prefab'
import 'src/entity/types/bullet-mortar-ball/prefab'

import 'src/entity/types/timer/prefab'
import 'src/entity/types/chat/prefab'
import 'src/entity/types/flag/prefab'

import 'src/entity/types/controller-ctf/prefab'
import 'src/entity/types/controller-dm/prefab'
import 'src/entity/types/controller-tdm/prefab'
import 'src/entity/types/controller-freeroam/prefab'

import 'src/entity/types/tank-bigboi/prefab'
import 'src/entity/types/tank-tesla/prefab'
import 'src/entity/types/tank-bomber/prefab'
import 'src/entity/types/tank-nasty/prefab'
import 'src/entity/types/tank-mortar/prefab'
import 'src/entity/types/tank-sniper/prefab'
import 'src/entity/types/tank-shotgun/prefab'
import 'src/entity/types/tank-monster/prefab'
import 'src/entity/types/tank-tiny/prefab'

import 'src/entity/types/weapon-flamethrower/prefab'
import 'src/entity/types/weapon-double-barreled/prefab'
import 'src/entity/types/weapon-shotgun/prefab'
import 'src/entity/types/weapon-single-barrelled/prefab'
import 'src/entity/types/weapon-stungun/prefab'

import 'src/entity/types/effect-flame/prefab'
import 'src/entity/types/effect-pellets/prefab'
import 'src/entity/types/effect-world-explosion/prefab'
import 'src/entity/types/effect-sound/prefab'

import 'src/entity/types/group/prefab'
import 'src/entity/types/tilemap/prefab'
import 'src/entity/types/spawn-zone/prefab'