import 'src/entity/types/bullet-16mm/server-prefab'
import 'src/entity/types/bullet-42mm/server-prefab'
import 'src/entity/types/bullet-bomb/server-prefab'
import 'src/entity/types/bullet-cannonball/server-prefab'
import 'src/entity/types/bullet-mine/server-prefab'
import 'src/entity/types/bullet-mortar-ball/server-prefab'

import 'src/entity/types/timer/server-prefab'
import 'src/entity/types/flag/server-prefab'
import 'src/entity/types/chat/server-prefab'

import 'src/entity/types/controller-ctf/server-prefab'
import 'src/entity/types/controller-dm/server-prefab'
import 'src/entity/types/controller-tdm/server-prefab'
import 'src/entity/types/controller-freeroam/server-prefab'

import 'src/entity/types/tank-bigboi/server-prefab'
import 'src/entity/types/tank-tesla/server-prefab'
import 'src/entity/types/tank-bomber/server-prefab'
import 'src/entity/types/tank-nasty/server-prefab'
import 'src/entity/types/tank-mortar/server-prefab'
import 'src/entity/types/tank-sniper/server-prefab'
import 'src/entity/types/tank-shotgun/server-prefab'
import 'src/entity/types/tank-monster/server-prefab'
import 'src/entity/types/tank-tiny/server-prefab'

import 'src/entity/types/weapon-flamethrower/server-prefab'
import 'src/entity/types/weapon-double-barreled/server-prefab'
import 'src/entity/types/weapon-shotgun/server-prefab'
import 'src/entity/types/weapon-single-barrelled/server-prefab'
import 'src/entity/types/weapon-stungun/server-prefab'

import 'src/entity/types/effect-flame/server-prefab'
import 'src/entity/types/effect-pellets/server-prefab'
import 'src/entity/types/effect-world-explosion/server-prefab'
import 'src/entity/types/effect-sound/server-prefab'

import 'src/entity/types/group/server-prefab'
import 'src/entity/types/tilemap/server-prefab'
import 'src/entity/types/spawn-zone/server-prefab'