
export const Commands = {
    PASS_BLOCK_TO_CHILD:     0xF000,
    BLOCK_UPDATE_COMMAND:    0x0F0B,
    HEALTH_UPDATE_COMMAND:   0x0F0C,
    POSITION_UPDATE_COMMAND: 0x0F0D,
    EFFECT_CREATE_COMMAND:   0x0F0E,
    EFFECT_REMOVE_COMMAND:   0x0F0F,
}