
export const Commands = {
    // Entity tree commands
    PASS_BLOCK_TO_CHILD:      0xF000,
    ENTITY_CREATE_COMMAND:    0xF001,
    ENTITY_REMOVE_COMMAND:    0xF002,

    // Component commands
    WORLD_PLAYER_STATISTICS_COMMAND: 0x0F00,
    WORLD_MAP_NAME_COMMAND:          0x0F01,
    WORLD_MATCH_TIMER_COMMAND:       0x0F02,
    COLLISION_IGNORE_LIST_ADD:       0x0F03,
    COLLISION_IGNORE_LIST_REMOVE:    0x0F04,
    PLAYER_TANK_SET:                 0x0F05,
    GAME_MAP_CONTENT_COMMAND:        0x0F06,
    BLOCK_UPDATE_COMMAND:            0x0F07,
    HEALTH_UPDATE_COMMAND:           0x0F08,
    POSITION_UPDATE_COMMAND:         0x0F09,
    EFFECT_CREATE_COMMAND:           0x0F10,
    EFFECT_REMOVE_COMMAND:           0x0F11,
    GAME_STATE_COMMAND:              0x0F12,
    ENTITY_PILOT_LIST_COMMAND:       0x0F13,
    TIMER_VALUE_COMMAND:             0x0F14,
}